In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("WineQT.csv")

In [4]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 107.3 KB

In [6]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
fixed acidity,1143.0,8.311111,1.747595,4.60000,7.10000,7.90000,9.100000,15.90000
volatile acidity,1143.0,0.531339,0.179633,0.12000,0.39250,0.52000,0.640000,1.58000
citric acid,1143.0,0.268364,0.196686,0.00000,0.09000,0.25000,0.420000,1.00000
residual sugar,1143.0,2.532152,1.355917,0.90000,1.90000,2.20000,2.600000,15.50000
chlorides,1143.0,0.086933,0.047267,0.01200,0.07000,0.07900,0.090000,0.61100
free sulfur dioxide,1143.0,15.615486,10.250486,1.00000,7.00000,13.00000,21.000000,68.00000
total sulfur dioxide,1143.0,45.914698,32.782130,6.00000,21.00000,37.00000,61.000000,289.00000
density,1143.0,0.996730,0.001925,0.99007,0.99557,0.99668,0.997845,1.00369
pH,1143.0,3.311015,0.156664,2.74000,3.20500,3.31000,3.400000,4.01000
sulphates,1143.0,0.657708,0.170399,0.33000,0.55000,0.62000,0.730000,2.00000
alcohol,1143.0,10.442111,1.082196,8.40000,9.50000,10.20000,11.100000,14.90000
quality,1143.0,5.657043,0.805824,3.00000,5.00000,6.00000,6.000000,8.00000

In [7]:
x = data.drop("quality", axis=1)
y = data["quality"]

In [8]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=44)

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [10]:
from sklearn.svm import SVC
svm_classifier = SVC()
svm_classifier.fit(x_train, y_train)    
y_pred = svm_classifier.predict(x_test)

In [11]:
y_pred

array([5, 6, 6, 7, 5, 6, 5, 7, 6, 6, 5, 6, 6, 6, 5, 6, 6, 6, 5, 5, 5, 5,
       5, 5, 5, 6, 6, 5, 6, 6, 6, 5, 7, 5, 6, 5, 6, 6, 6, 5, 5, 5, 6, 5,
       5, 5, 5, 6, 5, 5, 5, 6, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6,
       5, 7, 5, 6, 6, 6, 5, 7, 6, 6, 5, 5, 5, 5, 6, 6, 5, 6, 5, 6, 6, 6,
       5, 5, 6, 5, 5, 6, 5, 5, 5, 5, 6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 5, 6,
       6, 6, 6, 5, 6, 5, 6, 5, 7, 5, 5, 6, 5, 7, 5, 6, 5, 6, 6, 5, 6, 6,
       6, 5, 6, 6, 5, 6, 7, 6, 5, 6, 6, 5, 5, 5, 5, 5, 5, 6, 5, 5, 6, 6,
       5, 5, 6, 5, 5, 5, 5, 6, 5, 6, 5, 5, 5, 6, 7, 7, 5, 5, 5, 6, 6, 5,
       7, 5, 6, 5, 6, 5, 6, 5, 5, 5, 6, 7, 6, 6, 6, 6, 6, 7, 5, 5, 7, 7,
       6, 6, 6, 5, 5, 5, 5, 6, 5, 5, 5, 5, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5,
       5, 6, 6, 6, 6, 6, 5, 7, 6])

In [12]:
svm_classifier.score(x_test, y_test)

0.6200873362445415

In [13]:
param_grid = {
    "C": [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto'],
    'degree': [2, 3, 4]
}

from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(estimator=svm_classifier, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)
grid_search.fit(x_train, y_train)

Fitting 5 folds for each of 72 candidates, totalling 360 fits

GridSearchCV(cv=5, estimator=SVC(), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10, 100], 'degree': [2, 3, 4],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'rbf', 'poly']},
             verbose=2)

In [14]:
grid_search.best_params_

{'C': 1, 'degree': 2, 'gamma': 'scale', 'kernel': 'rbf'}

In [15]:
from sklearn.svm import SVC
model = SVC(C=1.0, degree=2, kernel="rbf", random_state=44, gamma="scale")
model.fit(x_train,y_train)
z_pred = model.predict(x_test)
z_pred

array([5, 6, 6, 7, 5, 6, 5, 7, 6, 6, 5, 6, 6, 6, 5, 6, 6, 6, 5, 5, 5, 5,
       5, 5, 5, 6, 6, 5, 6, 6, 6, 5, 7, 5, 6, 5, 6, 6, 6, 5, 5, 5, 6, 5,
       5, 5, 5, 6, 5, 5, 5, 6, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6,
       5, 7, 5, 6, 6, 6, 5, 7, 6, 6, 5, 5, 5, 5, 6, 6, 5, 6, 5, 6, 6, 6,
       5, 5, 6, 5, 5, 6, 5, 5, 5, 5, 6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 5, 6,
       6, 6, 6, 5, 6, 5, 6, 5, 7, 5, 5, 6, 5, 7, 5, 6, 5, 6, 6, 5, 6, 6,
       6, 5, 6, 6, 5, 6, 7, 6, 5, 6, 6, 5, 5, 5, 5, 5, 5, 6, 5, 5, 6, 6,
       5, 5, 6, 5, 5, 5, 5, 6, 5, 6, 5, 5, 5, 6, 7, 7, 5, 5, 5, 6, 6, 5,
       7, 5, 6, 5, 6, 5, 6, 5, 5, 5, 6, 7, 6, 6, 6, 6, 6, 7, 5, 5, 7, 7,
       6, 6, 6, 5, 5, 5, 5, 6, 5, 5, 5, 5, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5,
       5, 6, 6, 6, 6, 6, 5, 7, 6])

In [16]:
model.score(x_test, y_test)

0.6200873362445415